[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32F411CEUx"

rustflags = [
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "linker=flip-link",
    "-Z",
    "trap-unreachable=no",
    "-C",
    "inline-threshold=5",
    "-C",
    "no-vectorize-loops",
]

[build]
target = "thumbv7em-none-eabihf"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]
